# Generated by Django 4.2.1 on 2023-06-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default='category', max_length=255),
            preserve_default=False,
        ),
    ]
