# Generated by Django 4.2.1 on 2023-06-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0002_productcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('MAIN', 'Main'), ('ADDITIONAL', 'Additional')], default='ADDITIONAL', max_length=20),
            preserve_default=False,
        ),
    ]
