# Generated by Django 4.2.1 on 2023-06-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0011_product_linked_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='linked_products',
            field=models.ManyToManyField(blank=True, null=True, to='user_interface.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
