# Generated by Django 4.2.1 on 2023-06-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0014_productimage_cropping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product_parameter', 'value')},
        ),
        migrations.AddField(
            model_name='product',
            name='product_attributes',
            field=models.ManyToManyField(blank=True, to='user_interface.productattribute'),
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
    ]
