# Generated by Django 4.2.1 on 2023-06-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0015_alter_productattribute_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='active',
            new_name='in_stock',
        ),
    ]
