# Generated by Django 4.2.1 on 2023-06-22 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_interface', '0018_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartAmmountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.PositiveIntegerField(default=1)),
                ('product_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.productparametervalue')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='user_interface.cartammountproduct'),
        ),
    ]
