# Generated by Django 4.2.1 on 2023-06-22 10:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_interface', '0019_cartammountproduct_alter_cart_products'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartammountproduct',
            unique_together={('user', 'product_parameter')},
        ),
    ]
