# Generated by Django 4.2.1 on 2023-06-22 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_interface', '0020_alter_cartammountproduct_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartammountproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
