# Generated by Django 4.2.1 on 2023-06-23 07:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_interface', '0021_alter_cartammountproduct_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartAmmountProduct',
            new_name='CartamountProduct',
        ),
        migrations.RenameField(
            model_name='cartamountproduct',
            old_name='ammount',
            new_name='amount',
        ),
    ]
