# Generated by Django 4.2.1 on 2023-06-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0022_rename_cartammountproduct_cartamountproduct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartamountproduct',
            options={'ordering': ['product_parameter__product__name']},
        ),
    ]
