# Generated by Django 4.2.1 on 2023-06-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0023_alter_cartamountproduct_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartamountproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cartamountproduct',
            name='product_parameter',
        ),
        migrations.RemoveField(
            model_name='cartamountproduct',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='linked_parameter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='linked_products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_attributes',
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product_parameter',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='content_type',
        ),
        migrations.AlterUniqueTogether(
            name='productparametervalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productparametervalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productparametervalue',
            name='product_parameter',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartamountProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductParameter',
        ),
        migrations.DeleteModel(
            name='ProductParameterValue',
        ),
    ]
